name: Build Image and Deploy Cloud Run

inputs:
  PROJECT_ID:
    required: true
  PROJECT_REGION:
    required: true
  WORKLOAD_IDENTITY_PROVIDER:
    required: true
  SERVICE_ACCOUNT:
    required: true
  SERVICE_NAME:
    required: true


runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      id: auth
      with:
        workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.SERVICE_ACCOUNT }}
    - name: Override
      shell: bash
      run: |
        echo "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=${{steps.auth.outputs.credentials_file_path}}" >> $GITHUB_ENV
        echo ${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE}}
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{steps.auth.outputs.credentials_file_path}}" >> $GITHUB_ENV
        echo ${{ env.GOOGLE_APPLICATION_CREDENTIALS}}
        echo "GOOGLE_GHA_CREDS_PATH=${{steps.auth.outputs.credentials_file_path}}" >> $GITHUB_ENV
        echo ${{ env.GOOGLE_GHA_CREDS_PATH}}

        echo "CLOUDSDK_PROJECT=${{steps.auth.outputs.project_id}}" >> $GITHUB_ENV
        echo "CLOUDSDK_CORE_PROJECT=${{steps.auth.outputs.project_id}}" >> $GITHUB_ENV
        echo "GCP_PROJECT=${{steps.auth.outputs.project_id}}" >> $GITHUB_ENV
        echo "GCLOUD_PROJECT=${{steps.auth.outputs.project_id}}" >> $GITHUB_ENV
        echo "GOOGLE_CLOUD_PROJECT=${{steps.auth.outputs.project_id}}" >> $GITHUB_ENV
        echo ${{ env.GOOGLE_GHA_CREDS_PATH}}
    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Get image path
      id: image-path
      shell: bash
      run: echo "::set-output name=IMAGE_URI::gcr.io/${{ inputs.PROJECT_ID }}/${{ inputs.SERVICE_NAME }}"
    - name: Build image
      shell: bash
      run: gcloud builds submit -t ${{ steps.image-path.outputs.IMAGE_URI }}
    - name: Deploy Cloud Run
      shell: bash
      run: |
        gcloud run deploy ${{ inputs.SERVICE_NAME }} --image ${{ steps.image-path.outputs.IMAGE_URI }} \
        --region ${{ inputs.PROJECT_REGION }} --no-allow-unauthenticated
