name: Deploy Microservice

on:
  pull_request:
    type: [ opened, synchronize ]

env:
  PROJECT_ID: side-project-336100
  PROJECT_REGION: us-west1
  SERVICE_NAME: sample-service
  WORKLOAD_IDENTITY_PROVIDER: projects/810281168299/locations/global/workloadIdentityPools/my-pool/providers/my-provider
  SERVICE_ACCOUNT: wip-service-account@side-project-336100.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Get image path
        id: image-path
        shell: bash
        run: echo "::set-output name=IMAGE_URI::gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}"
      - name: Build image
        shell: bash
        run: gcloud builds submit -t ${{ steps.image-path.outputs.IMAGE_URI }} --region ${{ env.PROJECT_REGION }}
      - name: Deploy Cloud Run
        shell: bash
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} --image ${{ steps.image-path.outputs.IMAGE_URI }} \
          --region ${{ env.PROJECT_REGION }} --no-allow-unauthenticated
